# Generated by Django 3.1.1 on 2020-09-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=50)),
                ('post_body', models.CharField(max_length=5000)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
