# Generated by Django 3.1.1 on 2020-09-15 11:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20200915_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
